name: vibration-app
services:
  - name: backend
    source_dir: backend
    run_command: 'python app.py'
    environment_slug: python
    http_port: 5001
    routes:
      - path: /api/*
      - path: /socket.io/*
        websocket: true
    envs:
      - key: FLASK_ENV
        value: production
      - key: MONGO_URI
        value: '${MONGO_URL}'
    instance_size_slug: basic-xxs
    dockerfile_path: ''

  - name: frontend
    source_dir: frontend
    environment_slug: static-site
    routes:
      - path: /
    instance_size_slug: basic-xxs

databases:
  - engine: mongodb
    production: true
